### PR TITLE
Thinning: allow custom input_shape parameter

### PR DESCRIPTION
**Pull request by trougnouf**
This PR adds an optional input_shape parameter to the FilterRemover / ChannelRemover. This allows thinning on any not predefined model. It can be defined in the yaml such as:
```
extensions:
  net_thinner:
    class: 'FilterRemover'
    thinning_func_str: remove_filters
    input_shape: [15, 3, 9, 1920]
```
I also removed the arch parameter which is not used.

### CODE REVIEW

**Comment by trougnouf** [comment]
The tests are not passing with my first attempt, I've uploaded the logs here and committed since I won't be working on this over the weekend.

[test_logs.zip](https://github.com/NervanaSystems/distiller/files/3487213/test_logs.zip)
[console_output.txt](https://github.com/NervanaSystems/distiller/files/3487215/console_output.txt)

**Comment by nzmora** [comment]
Hi @trougnouf,
Please let me know if you plan to pursue this PR.
Thanks!
Neta

**Comment by trougnouf** [comment]
Hi @nzmora ,
Sorry I won't be pursuing this further. I think I implemented the changes needed but I can't get the tests to pass (in either master or this branch) and I'm not using thinning at the moment.
Best,
Benoit

**Comment by xerus** [comment]
Hi, I would like to "finish" this PR. Should I cherry-pick the commits, rebase & fix the issues and open a new PR? Also I don't think removing "arch" is desired - since it would break existing environments. imo making it optional is a safer way.

**Pull request closed without merging**
